# cloudbuild.yaml - Google Cloud Build configuration for EduChat
# Project: educhat-482804
# Artifact Registry: asia-southeast2-docker.pkg.dev/educhat-482804/educhat

substitutions:
  _IMAGE_TAG: 'latest'
  _REGION: 'asia-southeast2'
  _SERVICE_NAME: 'educhat'

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast2-docker.pkg.dev/${PROJECT_ID}/educhat/educhat:${_IMAGE_TAG}'
      - '.'

  # Step 2: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast2-docker.pkg.dev/${PROJECT_ID}/educhat/educhat:${_IMAGE_TAG}'

  # Step 3: Deploy to Cloud Run with .env from Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'asia-southeast2-docker.pkg.dev/${PROJECT_ID}/educhat/educhat:${_IMAGE_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      # Mount entire .env file from Secret Manager
      - '--set-secrets'
      - '/app/.env=educhat-env:latest'

# Store images in Artifact Registry
images:
  - 'asia-southeast2-docker.pkg.dev/${PROJECT_ID}/educhat/educhat:${_IMAGE_TAG}'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout (15 minutes)
timeout: '900s'
